name: demo-workflow
on: 
  workflow_dispatch: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]

env: 
  FULL_NAME: 'Emmanuel Sahr Sewah'
  OCCUPATION: 'Software Developer'

jobs:
  greeter:
    name: Greeter Job
    runs-on: ubuntu-latest
    steps:
      - name: kind-greeter
        uses: ./.github/workflow/composite/test
        with:
          name: $FULL_NAME

#  greeter:
#    name: "Greeter Job"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Greet
#        run: echo Hello $FULL_NAME
